---
abstract: 'MongoDB document to Moose object mapper'
author:
  - 'Rodrigo de Oliveira <rodrigolive@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102340, CPAN::Meta::Converter version 2.102160'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mongoose
requires:
  Carp: 0
  List::Util: 0
  Module::Pluggable: 3.5
  MongoDB: 0.35
  Moose: 0.9
  MooseX::Role::Parameterized: 0.16
  MooseX::Singleton: 0
  Params::Coerce: 0
  Scalar::Util: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Mongoose
  homepage: http://search.cpan.org/perldoc?Mongoose
  repository: git://github.com/rodrigolive/mongoose.git
version: 0.04
